
## LabDS01 ##


The following dataset includes information about several countries. This information was collected by the world bank (https://data.worldbank.org/). Data corresponds to 2016.

`
dataFile="https://raw.githubusercontent.com/masterfloss/data/main/worlddata2016.xlsx"
df=pd.read_excel(dataFile)
`

# 1. Business Understanding

Purpose: Analyse data and extract knowledge

Observation: Country

# 2. Data Undertanding

* Discuss the data and purposes
* What are the main limitations?

In [1]:
import pandas as pd
import numpy as np
# Import data
file="https://raw.githubusercontent.com/masterfloss/data/main/worlddata2016.xlsx"
df=pd.read_excel(file)
# Verify shape
# df.shape
# verify name and varible type
df.head()

,Unnamed: 0,Country Name,Indicator Name,2016
0,0,Afghanistan,Access to clean fuels and technologies for coo...,32.44000
1,1,Afghanistan,Access to electricity (% of population),97.70000
2,2,Afghanistan,"Access to electricity, rural (% of rural popul...",97.09936
3,3,Afghanistan,"Access to electricity, urban (% of urban popul...",99.50000
4,4,Afghanistan,Account ownership at a financial institution o...,NaN

In [2]:
# Pivot date. The name of the 
# df1=dfOriginal.pivot_table(dfOrigina,value='nameOf Column with values',index=['indexColumnName'],columns=['ColumnWhereDolumnNamesAre'])

df1 = pd.pivot_table(df, values='2016', index=['Country Name'],columns=['Indicator Name'])
# verify result
df1.head()

Indicator Name,ARI treatment (% of children under 5 taken to a health provider),Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adequacy of social insurance programs (% of total welfare of beneficiary households),Adequacy of social protection and labor programs (% of total welfare of beneficiary households),Adequacy of social safety net programs (% of total welfare of beneficiary households),Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households),"Adjusted net enrollment rate, primary (% of primary school age children)",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),Young people (ages 15-24) newly infected with HIV
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,32.44,97.700000,97.099360,99.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.7,500.0
Albania,NaN,77.42,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,97.65542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.6,100.0
Algeria,NaN,92.62,99.990051,99.965142,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.4,500.0
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,100.00,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df1.shape

(217, 1328)

In [4]:
df1.index.name = 'country'

# 3. Data Preparation

* Converting data to numeric
* Missing Values Imputation
* Normalization
* Variable Dummification
* Data balancing
* Pivot date in order to convert the values "Indicator Name" into comuns 
* Remove all columns that have no values, df1[columns].sum()==0
* Remove all columns that have more than 210 observations, df1[columns].count()<210

In [5]:
#remove all columns that have no values, df1[columns].sum()==0
df2=df1
for columns in df2:
    if(df2[columns].sum()==0):
        df2=df2.drop([columns], axis=1)

In [6]:
df2.head()

Indicator Name,ARI treatment (% of children under 5 taken to a health provider),Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)",Adequacy of social insurance programs (% of total welfare of beneficiary households),Adequacy of social protection and labor programs (% of total welfare of beneficiary households),Adequacy of social safety net programs (% of total welfare of beneficiary households),Adequacy of unemployment benefits and ALMP (% of total welfare of beneficiary households),"Adjusted net enrollment rate, primary (% of primary school age children)",...,Women who believe a husband is justified in beating his wife (any of five reasons) (%),Women who believe a husband is justified in beating his wife when she argues with him (%),Women who believe a husband is justified in beating his wife when she burns the food (%),Women who believe a husband is justified in beating his wife when she goes out without telling him (%),Women who believe a husband is justified in beating his wife when she neglects the children (%),Women who believe a husband is justified in beating his wife when she refuses sex with him (%),Women who were first married by age 15 (% of women ages 20-24),Women who were first married by age 18 (% of women ages 20-24),Women's share of population ages 15+ living with HIV (%),Young people (ages 15-24) newly infected with HIV
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,32.44,97.700000,97.099360,99.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.7,500.0
Albania,NaN,77.42,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,97.65542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.6,100.0
Algeria,NaN,92.62,99.990051,99.965142,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.4,500.0
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,100.00,100.000000,100.000000,100.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# converte all zeros into nan
df2=df2.replace(0,np.nan)

In [8]:
#remove all columns that have more than 210 observations, df1[columns].count()<210
for column1 in df2:
    if df2[column1].count()<210:
        df2=df2.drop([column1],axis=1)

In [9]:
df2.shape

(217, 18)

In [10]:
df2.head()

Indicator Name,Access to electricity (% of population),"Access to electricity, urban (% of urban population)",Agricultural land (sq. km),Capture fisheries production (metric tons),Land area (sq. km),People using at least basic drinking water services (% of population),Population density (people per sq. km of land area),Population growth (annual %),"Population, total",Secure Internet servers,Secure Internet servers (per 1 million people),Surface area (sq. km),Terrestrial and marine protected areas (% of total territorial area),Terrestrial protected areas (% of total land area),Total fisheries production (metric tons),Urban population,Urban population (% of total population),Urban population growth (annual %)
country,,,,,,,,,,,,,,,,,,
Afghanistan,97.700000,99.5,379100.000000,1000.0,652860.0,64.286484,54.197114,2.778317,35383128.0,426.0,12.039637,652860.0,0.104707,0.10,2200.0,8852859.0,25.020,3.649410
Albania,100.000000,100.0,11816.999512,7885.7,27400.0,91.020370,104.967190,-0.159880,2876101.0,416.0,144.640261,28750.0,13.147749,17.21,8835.7,1680247.0,58.421,1.544014
Algeria,99.990051,100.0,413601.992188,95000.0,2381740.0,93.515851,17.025957,2.051355,40551404.0,309.0,7.619958,2381740.0,7.105500,7.50,96361.0,28977628.0,71.459,2.910068
American Samoa,NaN,NaN,49.000001,3047.0,200.0,99.696437,278.705000,-0.127294,55741.0,10.0,179.401159,200.0,8.708522,4.27,3067.0,48605.0,87.198,-0.172673
Andorra,100.000000,100.0,187.800007,NaN,470.0,100.000000,164.461702,-0.919470,77297.0,219.0,2833.227680,470.0,21.190930,21.19,NaN,68213.0,88.248,-1.029674

In [11]:
# remove all row with na

df2=df2.dropna()
df2.shape

(194, 18)

In [12]:
# create a list with all the names of countries
countriesList=type(list(df2.index))

In [13]:
from sklearn.preprocessing import StandardScaler
df2St=StandardScaler().fit_transform(df2)

In [14]:
from sklearn.decomposition import PCA

In [15]:
pcaModel=PCA(n_components=4)

In [16]:
features_pca=pcaModel.fit_transform(df2St)

In [17]:
colList=[]
for col1 in df2:
    colList.append(col1)
colList

['Access to electricity (% of population)',
 'Access to electricity, urban (% of urban population)',
 'Agricultural land (sq. km)',
 'Capture fisheries production (metric tons)',
 'Land area (sq. km)',
 'People using at least basic drinking water services (% of population)',
 'Population density (people per sq. km of land area)',
 'Population growth (annual %)',
 'Population, total',
 'Secure Internet servers',
 'Secure Internet servers (per 1 million people)',
 'Surface area (sq. km)',
 'Terrestrial and marine protected areas (% of total territorial area)',
 'Terrestrial protected areas (% of total land area)',
 'Total fisheries production (metric tons)',
 'Urban population',
 'Urban population (% of total population)',
 'Urban population growth (annual %)']

In [18]:
scores=pcaModel.components_.T
scores

array([[ 0.12653359, -0.42307385, -0.10307775, -0.01924474],
       [ 0.12092738, -0.39106253, -0.1099584 , -0.0351517 ],
       [ 0.36982485,  0.11046688,  0.09881341,  0.17494864],
       [ 0.37831737,  0.09640299, -0.10818644, -0.21470283],
       [ 0.33481092,  0.0843069 ,  0.15294993,  0.35502944],
       [ 0.11800878, -0.42501147, -0.06609072, -0.00436037],
       [-0.0073808 , -0.0829522 , -0.01350044,  0.0048247 ],
       [-0.09017389,  0.34783848,  0.06948714,  0.11455117],
       [ 0.34993334,  0.12112976, -0.13302206, -0.26340022],
       [ 0.18208022, -0.03219886,  0.27067408,  0.35942388],
       [ 0.04643012, -0.18229946,  0.16845682,  0.19270923],
       [ 0.33391583,  0.08273703,  0.15420647,  0.35987425],
       [ 0.02423518, -0.03687318,  0.63116582, -0.30424225],
       [-0.00609623, -0.09064153,  0.57826905, -0.3873216 ],
       [ 0.34337557,  0.10429461, -0.15349449, -0.33215745],
       [ 0.39252393,  0.10293315, -0.08547639, -0.20294625],
       [ 0.09000422, -0.29489969,  0.11329538,  0.14989805],
       [-0.07274589,  0.39644095,  0.05881056,  0.02648438]])

In [19]:
dfscores=pd.DataFrame(scores)

In [20]:
dfscores['variables']=colList

In [21]:
dfscores

,0,1,2,3,variables
0,0.126534,-0.423074,-0.103078,-0.019245,Access to electricity (% of population)
1,0.120927,-0.391063,-0.109958,-0.035152,"Access to electricity, urban (% of urban popul..."
2,0.369825,0.110467,0.098813,0.174949,Agricultural land (sq. km)
3,0.378317,0.096403,-0.108186,-0.214703,Capture fisheries production (metric tons)
4,0.334811,0.084307,0.152950,0.355029,Land area (sq. km)
5,0.118009,-0.425011,-0.066091,-0.004360,People using at least basic drinking water ser...
6,-0.007381,-0.082952,-0.013500,0.004825,Population density (people per sq. km of land ...
7,-0.090174,0.347838,0.069487,0.114551,Population growth (annual %)
8,0.349933,0.121130,-0.133022,-0.263400,"Population, total"
9,0.182080,-0.032199,0.270674,0.359424,Secure Internet servers
10,0.046430,-0.182299,0.168457,0.192709,Secure Internet servers (per 1 million people)
11,0.333916,0.082737,0.154206,0.359874,Surface area (sq. km)
12,0.024235,-0.036873,0.631166,-0.304242,Terrestrial and marine protected areas (% of t...
13,-0.006096,-0.090642,0.578269,-0.387322,Terrestrial protected areas (% of total land a...
14,0.343376,0.104295,-0.153494,-0.332157,Total fisheries production (metric tons)
15,0.392524,0.102933,-0.085476,-0.202946,Urban population
16,0.090004,-0.294900,0.113295,0.149898,Urban population (% of total population)
17,-0.072746,0.396441,0.058811,0.026484,Urban population growth (annual %)

In [22]:
#dfscores=dfscores.set_index(['variables'])

In [23]:
dfscores

,0,1,2,3,variables
0,0.126534,-0.423074,-0.103078,-0.019245,Access to electricity (% of population)
1,0.120927,-0.391063,-0.109958,-0.035152,"Access to electricity, urban (% of urban popul..."
2,0.369825,0.110467,0.098813,0.174949,Agricultural land (sq. km)
3,0.378317,0.096403,-0.108186,-0.214703,Capture fisheries production (metric tons)
4,0.334811,0.084307,0.152950,0.355029,Land area (sq. km)
5,0.118009,-0.425011,-0.066091,-0.004360,People using at least basic drinking water ser...
6,-0.007381,-0.082952,-0.013500,0.004825,Population density (people per sq. km of land ...
7,-0.090174,0.347838,0.069487,0.114551,Population growth (annual %)
8,0.349933,0.121130,-0.133022,-0.263400,"Population, total"
9,0.182080,-0.032199,0.270674,0.359424,Secure Internet servers
10,0.046430,-0.182299,0.168457,0.192709,Secure Internet servers (per 1 million people)
11,0.333916,0.082737,0.154206,0.359874,Surface area (sq. km)
12,0.024235,-0.036873,0.631166,-0.304242,Terrestrial and marine protected areas (% of t...
13,-0.006096,-0.090642,0.578269,-0.387322,Terrestrial protected areas (% of total land a...
14,0.343376,0.104295,-0.153494,-0.332157,Total fisheries production (metric tons)
15,0.392524,0.102933,-0.085476,-0.202946,Urban population
16,0.090004,-0.294900,0.113295,0.149898,Urban population (% of total population)
17,-0.072746,0.396441,0.058811,0.026484,Urban population growth (annual %)

In [24]:
def selectColor(val):
    if (val > 0.3 or val<-0.3):
        color = 'red' 
    else:
        color = 'black'
    return 'color: %s' % color

df_pintado = dfscores.style.applymap(selectColor)
df_pintado

TypeError: '>' not supported between instances of 'str' and 'float'

In [25]:
# 0 "grande" pequeno - grande 
# 1 "fracas infraestruturas e crescimento" fraca- boas infraestruturas e crescimento urbano 
# 2 "protecção da natureza" 
# 3 densidade populacional com internet segura